language: cpp

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install cmake
    fi
  - cmake --version

jobs:
  include:
    - name: "Android"
      script: Library/Support/Travis/CMake.sh NanoTest Android
      dist: bionic
      os: linux

    - name: "iOS"
      script: Library/Support/Travis/Xcode.sh Nano iOS
      osx_image: xcode11.3
      os: osx

    - name: "Linux"
      script: Library/Support/Travis/CMake.sh NanoTest Linux
      dist: bionic
      os: linux

    - name: "macOS"
      script: Library/Support/Travis/Xcode.sh NanoTest macOS
      osx_image: xcode11.3
      os: osx

    - name: "tvOS"
      script: Library/Support/Travis/Xcode.sh Nano tvOS
      osx_image: xcode11.3
      os: osx

    - name: "Windows"
      script: Library/Support/Travis/CMake.sh NanoTest Windows
      os: windows
