language: cpp

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.17.1/cmake-3.17.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

jobs:
  include:
    - name: "Android"
      script: Library/Support/Travis/CMake.sh NanoTest Android
      dist: bionic
      os: linux

    - name: "iOS"
      script: Library/Support/Travis/Xcode.sh Nano iOS
      osx_image: xcode11.3
      os: osx

    - name: "Linux"
      script: Library/Support/Travis/CMake.sh NanoTest Linux
      dist: bionic
      os: linux

    - name: "macOS"
      script: Library/Support/Travis/Xcode.sh NanoTest macOS
      osx_image: xcode11.3
      os: osx

    - name: "tvOS"
      script: Library/Support/Travis/Xcode.sh Nano tvOS
      osx_image: xcode11.3
      os: osx

    - name: "Windows"
      script: Library/Support/Travis/CMake.sh NanoTest Windows
      os: windows
