name: Build tvOS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        config: ['Debug', 'Release']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          xcodebuild build                                       \
            -project Library/Project/Nano.xcodeproj              \
            -scheme      "Nano_tvOS - ${{ matrix.config }}"      \
            -destination "generic/platform=tvOS"                 \
            -parallelizeTargets                                  \
            Nano="${GITHUB_WORKSPACE}"                           \
            SYMROOT="${GITHUB_WORKSPACE}/Build" | xcpretty
