name: Build

on:
  push:
    branches: [master]

jobs:
  macos:
    runs-on: macOS-latest

    strategy:
      matrix:
        run-config:
          - { scheme: 'NanoTest_macOS - Debug',   destination: 'generic/platform=macOS' }
#          - { scheme: 'NanoTest_macOS - Release', destination: 'generic/platform=macOS' }
#          - { scheme: 'NanoTest_iOS - Debug',     destination: 'generic/platform=iOS' }
#          - { scheme: 'NanoTest_iOS - Release',   destination: 'generic/platform=iOS' }
#          - { scheme: 'NanoTest_tvOS - Debug',    destination: 'generic/platform=tvOS' }
#          - { scheme: 'NanoTest_tvOS - Release',  destination: 'generic/platform=tvOS' }

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Build Project
        run: |
          xcodebuild build -project NanoTest/Project/NanoTest.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -enableAddressSanitizer YES -enableUndefinedBehaviorSanitizer YES Nano="${GITHUB_WORKSPACE}" SYMROOT="${GITHUB_WORKSPACE}/Build" | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run Tests
        run: env

      - name: Run Tests
        run: ls -l "$GITHUB_WORKSPACE"




  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        run-config:
          - { config: 'Debug' }
          - { config: 'Release' }

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Prepare Build
        run: |
          ls -l
          mkdir -p "${GITHUB_WORKSPACE}/Build/'${{ matrix.run-config['config'] }}'"
          cd       "${GITHUB_WORKSPACE}/Build/'${{ matrix.run-config['config'] }}'"
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="'${{ matrix.run-config['config'] }}'" "${GITHUB_WORKSPACE}"
          
      - name: Build Project
        run: |
          cd "${GITHUB_WORKSPACE}/Build/'${{ matrix.run-config['config'] }}'"
          make -j2 "NanoTest"
          
      - name: Run Tests
        run: |
          cd "${GITHUB_WORKSPACE}/Build/'${{ matrix.run-config['config'] }}'"
          find . -name NanoTest
