name: Build macOS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        config: ['Debug', 'Release']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          xcodebuild build                                       \
            -project NanoTest/Project/NanoTest.xcodeproj         \
            -scheme      "NanoTest_macOS - ${{ matrix.config }}" \
            -destination "generic/platform=macOS"                \
            -parallelizeTargets                                  \
            -enableAddressSanitizer           YES                \
            -enableUndefinedBehaviorSanitizer YES                \
            Nano="${GITHUB_WORKSPACE}"                           \
            SYMROOT="${GITHUB_WORKSPACE}/Build" | xcpretty
          mv "Build/${{ matrix.config }}/NanoTest_macOS" "NanoTest_${{ matrix.config }}_macOS"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: NanoTest
          path: "NanoTest_${{ matrix.config }}_macOS"
          retention-days: 1

