name: Build

on:
  push:
    branches: [master]

jobs:
  macos:
    runs-on: macOS-latest

    strategy:
      matrix:
        run-config:
          - { scheme: 'NanoTest_macOS - Debug',   destination: 'generic/platform=macOS' }
#          - { scheme: 'NanoTest_macOS - Release', destination: 'generic/platform=macOS' }
#          - { scheme: 'NanoTest_iOS - Debug',     destination: 'generic/platform=iOS' }
#          - { scheme: 'NanoTest_iOS - Release',   destination: 'generic/platform=iOS' }
#          - { scheme: 'NanoTest_tvOS - Debug',    destination: 'generic/platform=tvOS' }
#          - { scheme: 'NanoTest_tvOS - Release',  destination: 'generic/platform=tvOS' }

    steps:
      - name: Show Files1
        run: xcpretty --version

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Show Files2
        run: ls -l

      - name: Build Project
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/Build"
          xcodebuild build -project NanoTest/Project/NanoTest.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -enableAddressSanitizer YES -enableUndefinedBehaviorSanitizer YES SYMROOT="${GITHUB_WORKSPACE}/Build" | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run Tests
        run: env

      - name: Run Tests
        run: ls -l "$GITHUB_WORKSPACE"




  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Prepare Build
        run: |
          ls -l
          mkdir -p "${GITHUB_WORKSPACE}/Build/Debug"
          cd       "${GITHUB_WORKSPACE}/Build/Debug"
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" "${GITHUB_WORKSPACE}"
          

      - name: Build Project
        run: |
          ls -l
          cd "${GITHUB_WORKSPACE}/Build/Debug"
          make -j2 "NanoTest"
