name: Build Linux

on:
  push:
    branches: [master]

jobs:
  Build_Linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config: ['Debug', 'Release']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CMake
        run: |
          mkdir Build
          cd    Build
          cmake -G "Unix Makefiles"                   \
            -DCMAKE_BUILD_TYPE="${{ matrix.config }}" \
            "${GITHUB_WORKSPACE}"

      - name: Build
        run: |
          cd Build
          make -j2 "NanoTest"
