name: Build

on:
  push:
    branches: [master]

jobs:
  macos:
    runs-on: macOS-latest

    strategy:
      matrix:
        run-config:
          - { scheme: 'NanoTest_macOS - Debug',   destination: 'generic/platform=macOS' }
          - { scheme: 'NanoTest_macOS - Release', destination: 'generic/platform=macOS' }
          - { scheme: 'NanoTest_iOS - Debug',     destination: 'generic/platform=iOS' }
          - { scheme: 'NanoTest_iOS - Release',   destination: 'generic/platform=iOS' }
          - { scheme: 'NanoTest_tvOS - Debug',    destination: 'generic/platform=tvOS' }
          - { scheme: 'NanoTest_tvOS - Release',  destination: 'generic/platform=tvOS' }

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Show Files
        run: ls -l

      - name: Build Project
        run: xcodebuild build -project NanoTest/Project/NanoTest.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -enableAddressSanitizer YES -enableUndefinedBehaviorSanitizer YES

      - name: Run Tests
        run: env
        


  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Show Files
        run: ls -l

      - name: Build Project
        run: cmake
