name: Test_macOS

on:
  push:
    branches: [master]

  workflow_run:
    workflows: ["Build_macOS"]
    types:
      - completed

jobs:
  Test_macOS:
    runs-on: macOS-latest

    strategy:
      matrix:
        config: ['Debug', 'Release']

    steps:
      - name: Download
        uses: dawidd6/action-download-artifact@v2
          workflow: build_macos.yml
          workflow_conclusion: success

      - name: Test
        run: |
          ls -lR
#          "NanoTest_${{ matrix.config }}_macOS" -d yes


