name: Test macOS

on:
  push:
    branches: [master]

  workflow_run:
    workflows: ["Build macOS"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macOS-latest

    strategy:
      matrix:
        config: ['Debug', 'Release']

    steps:
      - name: Download
        uses: actions/download-artifact@v2

      - name: Test
        run: |
          ls -lR Build
          "NanoTest_${{ matrix.config }}_macOS" -d yes
