name: Test Linux

on:
  push:
    branches: [master]

  workflow_run:
    workflows: ["Build Linux"]
    types:
      - completed

jobs:
  Test Linux:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        config: ['Debug', 'Release']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CMake
        run: |
          mkdir Build
          cd    Build
          cmake -G "Unix Makefiles"                   \
            -DCMAKE_BUILD_TYPE="${{ matrix.config }}" \
            "${GITHUB_WORKSPACE}"

      - name: Build
        run: |
          cd Build
          make -j2 "NanoTest"

      - name: Test
        run: |
          cd Build
          ./NanoTest/Project/NanoTest -d yes
