name: Test macOS

on:
  push:
    branches: [master]

  workflow_run:
    workflows: ["Build_macOS"]
    types:
      - completed

jobs:
  Test_macOS:
    runs-on: macOS-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        config: ['Debug', 'Release']

    steps:
      - name: Download
        uses: actions/download-artifact@v2

      - name: Test
        run: |
          ls -lR
          "NanoTest_${{ matrix.config }}_macOS" -d yes
