name: Test iOS

on:
  push:
    branches: [master]

  workflow_run:
    workflows: ["Build_iOS"]
    types:
      - completed

jobs:
  Test_iOS:
    runs-on: macOS-latest

    strategy:
      matrix:
        config: ['Debug', 'Release']

    steps:
      - name: Test
        run: |
          cd Build
          exit 1
